# POST http://localhost:8000/api/core/login/
# Content-Type: application/json

# {
#     "username":"Alaba",
#     "password":"password"
# }


# POST  http://localhost:8000/api/core/accounts/register/
# Content-Type: application/json

# {
#     "username":,
#     "first_name":,
#     "last_name":,
#     "phone_number":,
#     "email":,
#     "password":,
#     "password_confirmation":
# }

# POST http://localhost:8000/api/core/logout/
# Authorization: Token baff546ede2543e6b4831674d483d8224db053c5

# PATCH  http://localhost:8000/api/core/accounts/update/
# Content-Type: application/json
# Authorization: Token 81a2e3bbc8e08e1531dc8372d86000a82b4a0815


# {
#     "username":,
#     "first_name":,
#     "last_name":,
#     "phone_number":,
#     "email":,
#     "password":,
#     "password_confirmation":
# }



# GET http://localhost:8000/api/core/view-profile/
# Authorization: Token 065018e7d24e514a44a111740d6a37fdfbe7111f
# Content-Type: application/json
# {
#   "first_name": "Idowu",
#   "last_name": "Ibraheem",
#   "email": "ibraheemidowu851@gmail.com",
#   "username": "Alaba",
#   "phone_number": "+2349155645315",
#   "farms_count": 5,
#   "bots_count": 1
# }



#  GET http://localhost:8000/api/farms/farms-list/
#  Authorization: Token 065018e7d24e514a44a111740d6a37fdfbe7111f


# #  GET http://localhost:8000/api/farms/farm-detail/1
#  Authorization: Token 065018e7d24e514a44a111740d6a37fdfbe7111f


#  GET http://localhost:8000/api/farms/farm-house-details/1
#  Authorization: Token 065018e7d24e514a44a111740d6a37fdfbe7111f

#   POST  http://localhost:8000/api/farms/farm-house/register-device/
#  Authorization: Token 065018e7d24e514a44a111740d6a37fdfbe7111f
# Content-Type: application/json

# {
#     "id":1,
#     "unique_id":"AviX Bot 1001",
#     "name":"My Bot"
# }

# POST http://localhost:8000/api/farms/add-house/
# Authorization: Token 065018e7d24e514a44a111740d6a37fdfbe7111f
# Content-Type: application/json

# {
#     "id":1,
#     "tracks":3,
#     "name":"New House",
#     "zones":{
#         "1":[1, 2, 3],
#         "2":[1, 2, 3],
#         "3":[1, 2, 3]
#     }
    

# }

