# Generated by Django 6.1.1 on 2026-10-01 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_type', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('population', models.IntegerField()),
                ('raring_starts_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tracks', models.PositiveIntegerField()),
                ('zones', models.JSONField(default=dict)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(default='AviX Bot', max_length=25)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='farms.house')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ammonia', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('zone_index', models.IntegerField()),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='farms.bot')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_readings', to='farms.farm')),
            ],
        ),
    ]
