# Generated by Django 6.1.1 on 2026-09-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_unique_id', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ammonia', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('zone_index', models.IntegerField()),
            ],
        ),
    ]
